# Generated by Django 2.0.1 on 2019-01-31 13:36

from django.db import migrations, models
import members.utils


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20190126_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTeamCaptain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('photo', models.ImageField(upload_to=members.utils.get_upload_path, verbose_name='photo')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='phone number')),
                ('is_retired', models.BooleanField(default=False, verbose_name='is member retired?')),
                ('description', models.CharField(max_length=75, verbose_name='description (department)')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'abstract': False,
            },
        ),
    ]
