# Generated by Django 2.0.1 on 2019-02-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_techteamcaptain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techleader', to='members.Member', verbose_name='tech team leader')),
            ],
            options={
                'verbose_name_plural': 'teach team leader',
                'verbose_name': 'teach team leader',
            },
        ),
        migrations.DeleteModel(
            name='TechTeamCaptain',
        ),
    ]
